// The shortcuts the zipper runs, in order: [keys, what they do].
// Taken from cheat-sheet.html; keep the two in step.
export const SHORTCUTS: readonly (readonly [string, string])[] = [
  ["tmux", "Start tmux"],
  ["tmux new -s work", "Start a new session named work"],
  ["tmux ls", "List running sessions"],
  ["tmux a -t work", "Attach to the session named work"],
  ["tmux a", "Attach to the most recent session"],
  ["tmux new -A -s main", "Attach to main, or create it if it isn’t there"],
  ["tmux kill-session -t work", "Close the session named work"],
  ["tmux kill-server", "Close every session and tmux itself"],
  ["C-a d", "Detach. Everything keeps running."],
  ["C-a s", "Pick a session from a list"],
  ["C-a $", "Rename this session"],
  ["C-a ( / )", "Previous / next session"],
  ["C-a L", "Back to the last session you used"],
  ["C-a c", "New window"],
  ["C-a ,", "Rename this window"],
  ["C-a n / p", "Next / previous window"],
  ["C-a 0 … 9", "Go to a window by its number"],
  ["C-a w", "Pick a window from all sessions"],
  ["C-a f", "Find a window by text on its screen"],
  ["C-a &", "Close this window (asks y/n)"],
  ["click status bar", "Switch to the window you click"],
  ["scroll status bar", "Step through windows"],
  ["C-a |", "Split side by side, in the same folder"],
  ["C-a -", "Split top and bottom, in the same folder"],
  ["C-a h j k l", "Move to the pane left, below, above, right"],
  ["C-a ← ↑ ↓ →", "Move to the pane in that direction"],
  ["C-a ;", "Back to the previous pane"],
  ["C-a o", "Next pane"],
  ["C-a q", "Show pane numbers; press one to jump there"],
  ["C-a z", "Zoom this pane to the whole window, and back"],
  ["C-a x", "Close this pane (asks y/n)"],
  ["C-a { / }", "Swap with the previous / next pane"],
  ["C-a !", "Move this pane into its own window"],
  ["C-a Space", "Cycle through the built-in layouts"],
  ["C-a M-1 … M-5", "Preset layouts: side by side, stacked, big pane on top, big pane on left, grid"],
  ["C-a : setw synchronize-panes", "Type into every pane in this window at once; run it again to stop"],
  ["C-a C-← ↑ ↓ →", "Resize by 1 cell (keep tapping within half a second to repeat)"],
  ["C-a M-← ↑ ↓ →", "Resize by 5 cells"],
  ["click a pane", "Make it the active pane"],
  ["drag a border", "Resize the panes on both sides"],
  ["right-click a pane", "Menu to split, zoom, swap or close"],
  ["scroll wheel", "Scroll back through the output"],
  ["C-a [", "Enter copy mode; scroll with arrows, PgUp, PgDn"],
  ["C-a PgUp", "Enter copy mode one page up"],
  ["C-s / C-r", "Search down / up (in copy mode)"],
  ["C-Space", "Start a selection (in copy mode)"],
  ["M-w", "Copy the selection and leave (in copy mode)"],
  ["q", "Leave copy mode"],
  ["C-a ]", "Paste what you copied last"],
  ["C-a =", "Pick from everything you copied"],
  ["tmux capture-pane -pS - > out.txt", "Save this pane’s whole scrollback to out.txt"],
  ["drag", "Select text; it is copied when you let go"],
  ["double / triple click", "Copy a word / a line"],
  ["Shift + drag", "Select with Ghostty instead of tmux"],
  ["C-a C-s", "Save all sessions now; do this before a reboot"],
  ["C-a C-r", "Restore the last save"],
  ["every 15 min", "Saved on its own while tmux runs"],
  ["tmux", "After a reboot, brings back the last save"],
  ["on restore", "vim, nvim, less, man, htop, top and tail start again; other panes come back as a shell in the same folder"],
  ["C-a ?", "List every key binding"],
  ["C-a /", "Press any key to see what it does"],
  ["C-a :", "Type a tmux command"],
  ["C-a C-a", "Send a real Ctrl+a, such as start of line in fish"],
  ["C-a t", "Show a big clock; any key closes it"],
  ["tmux source ~/.tmux.conf", "Reload your config after editing it"],
  ["C-a I", "Install plugins listed in ~/.tmux.conf"],
  ["C-a U", "Update plugins"],
]
